name: comment

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  id-token: write

jobs:
  publish_call:
    uses: ./.github/workflows/publish.yml
  publish:
    needs: publish_call
    runs-on: ubuntu-latest
    if: |
        ${{ github.event.issue.pull_request }}
        && (github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'MEMBER')
        && contains(github.event.comment.body, '/release')
    steps:
      - run: echo "publish done"
